---
title: "Proposal"
author: Jacob Shoemaker; jshoemaker2249, Qinwen Yang; AngelQinwen, Laurel Baar; ljbaar109,
  Hongsheng Yin; simonhsy
date: "3/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Group Members:
Jacob Shoemaker
Qinwen Yang
Laurel Baar
Hongsheng Yin

Project Coordinator: Jacob Shoemaker, jshoemaker249

Dataset: Olympic History: Athletes and Results

Link to dataset: [link](https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results)

Overview of dataset: This dataset, of 15 columns, contains basic information about the past 120 years(from Athens 1896 to Rio 2016) of Olympic Games. Columns range from athlete name and information, event, year, medal, and location.


Exploratory Analysis Plan: From this dataset, we hope to examine the relationship between athletes and their respective performance. Questions we could potentially investigate?

- Which particular country produces the most gold medalists for any given sport?
- Is there evidence of the Russian Doping Scandal in this dataset?
-Does the body composition such as weight or height would effect the skater's speed skating？
-Compare from 1896 to 2016, is there any change for sports in Olympic games?
-What is the median height or weight for medal(gold) winners?

- Is there any similar point among the gold medal earners(For example, relationships with cities, height, weight.)?
- Which continent get most gold medals?  



